configserver:
    name: ECAS Consul Service
    status: Connected to ECAS Consul Server

jhipster:
    security:
        authentication:
            jwt:
                secret: 6bb16f64aed0feeff00ae875de5ef338
